services:
  mongo:
    image: mongo:8
    ports:
      - "27017:27017"

  pdf-extractext-persistence:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - APP_ENV=local
      - APP_PORT=8002
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo